roles:
  - src: geerlingguy.docker
  - src: geerlingguy.pip
  - name: simplificator.netdata_installation
    src: git@github.com:simplificator/ansible-role-netdata_installation.git
    scm: git
    version: master

collections:
  - community.docker
